[package]
name = "rustling-core"
version = "0.9.1"
authors = ["hdlj <hubert.delajonquiere@snips.net>", "Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
regex = "1.3"
smallvec = "1.4"
failure = "0.1"
string-interner = "0.12"
serde = { version = "1.0", features = ["derive"] }
